# Numpy

In [8]:
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [6]:
#verificando o tipo de dado: Lista e Numpy Array

print(type(list1))
print(type(arr1d))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

--------- lists ----------

<class 'list'>
[1, 2, 3, 4.5, 5.7]
<class 'int'>
<class 'float'>


--------- array ----------

<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.7]
<class 'numpy.float64'>
<class 'numpy.float64'>


## ndarray

In [10]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
print(arr1.shape)
print(arr1.dtype)

(5,)
float64


In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print(arr2.size)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32
8


In [13]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print(data4)
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[6.  7.5]
 [8.  1. ]]


In [14]:
data6 = np.arange(15)
print(data6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
data7 = np.eye(5)
print(data7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [17]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [18]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [19]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [20]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Operações entre arrays e escalares

In [21]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Escalar dividindo array: \n',1/arr3)
print('Array elevado ao quadrado: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
Array elevado ao quadrado: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Fatiamento

In [23]:
arr = [2,14,3,6,8,3,10,222,4]
arr = np.array(arr)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

[  2  14   3   6   8   3  10 222   4]
3
[  3  10 222]
[ 2 14  3  6  8 12 12 12  4]


In [24]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[12 12 12]
[   12 12345    12]
[    2    14     3     6     8    12 12345    12     4]


In [25]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2]) #igual a print(arr2d[0, 2])

[7 8 9]
3


In [26]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

[[2 3]
 [5 6]]
[4 5]
[[1]
 [4]
 [7]]


## Transposição

In [27]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Flattening

In [28]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
b2 = arr2d.ravel() 
b2[0] = 101
print(arr2d)

----- flatten() -----

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

----- ravel() -----

[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


## Funções Universais

In [30]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr)) #raiz quadrada
np.exp(arr) #e^x

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## Localização baseada em Condição e Métodos Estatísticos

In [31]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
import timeit

In [32]:
%timeit result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
#result

1.42 µs ± 7.02 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
%timeit result = np.where(cond, xarr, yarr)
#result

726 ns ± 6.55 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [34]:
arr = np.random.randn(4, 4)
print(arr)
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

[[ 2.35900903 -0.04310628 -1.09111339 -1.14676911]
 [ 0.66898151  0.54306762 -0.80558682  0.3578611 ]
 [ 0.06317451  1.01455039  0.08816785 -0.94929931]
 [ 1.4464074   0.22075264 -1.13524699  0.59018306]]
[[ 2 -2 -2 -2]
 [ 2  2 -2  2]
 [ 2  2  2 -2]
 [ 2  2 -2  2]]
[[ 2.         -0.04310628 -1.09111339 -1.14676911]
 [ 2.          2.         -0.80558682  2.        ]
 [ 2.          2.          2.         -0.94929931]
 [ 2.          2.         -1.13524699  2.        ]]


In [35]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean()) #ou np.mean(arr)
print(arr.sum())
print(arr.mean(axis=1))
print(arr.sum(0))

[[-0.10229728 -0.65844366 -0.43993158  1.52723128]
 [ 0.48384831  0.66973635 -0.35048469 -0.25301555]
 [-0.68619574 -0.85438573  0.39886947  0.97848249]
 [-0.75179869  0.00524305 -0.84629503  1.24364834]
 [-0.34760172  1.80747598  1.46523069 -0.36168828]]
0.14638140016039608
2.927628003207922
[ 0.08163969  0.13752111 -0.04080738 -0.08730058  0.64085417]
[-1.40404512  0.96962599  0.22738886  3.13465827]


## Álgebra Linear

In [36]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
[[ 28.  64.]
 [ 67. 181.]]


In [37]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print(mat)
print(inv(mat)) #inversa

[[-0.15824434 -0.77154089 -0.95240377  0.98141495 -0.17981256]
 [ 0.50703083  1.39356946 -0.20680072 -0.12342616 -1.30380792]
 [-1.03171573  0.40801642  0.4084382   0.76363038 -0.23641482]
 [-0.3743585   1.29880859  1.00268857  0.14120307 -0.68938418]
 [ 0.78355767 -1.53413477 -0.09044196  0.27601569 -1.68937182]]
[[ 2.10066579 -1.2805854  -0.82176543 -0.84232007 -1.45434702]
 [-1.2805854   6.74426183  2.05432746 -0.85768046 -0.07832933]
 [-0.82176543  2.05432746  2.13022535 -0.48066356 -0.1941258 ]
 [-0.84232007 -0.85768046 -0.48066356  1.65766364 -0.75971655]
 [-1.45434702 -0.07832933 -0.1941258  -0.75971655  5.11736732]]
[[16.89430502  2.86948388  8.00450279 15.82694773  7.49854743]
 [ 2.86948388  0.70193021  1.16587957  2.74504968  1.27799973]
 [ 8.00450279  1.16587957  4.47891255  7.61616936  3.59330269]
 [15.82694773  2.74504968  7.61616936 15.54502833  7.13671702]
 [ 7.49854743  1.27799973  3.59330269  7.13671702  3.54186609]]


## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [39]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

array([0.37998728, 0.2517545 , 0.0211029 , 0.69780973])

In [40]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(42) # reset seed
print(np.random.random())

0.3745401188473625
0.3745401188473625


In [42]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
np.random.shuffle(x)
x

array([0, 8, 6, 3, 1, 4, 5, 2, 9, 7])

## Vectorize

In [43]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

x = 10 retorna  5.0
x = 11 retorna  121


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [44]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] retorna  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] retorna  [[  5. 121.   6.]
 [  1.   1.   9.]]


## Aplicar uma função – coluna ou linha

In [49]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [50]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Por linha:  [8 8 6 8]
Por coluna:  [7 8 2 7 6 5 8 5 5 5]


## Outros Métodos

In [54]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

True
False


In [55]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place
print(arr)

[-0.46402358 -0.05702664  0.27592974  1.49451522  0.56682064 -2.30337426
  1.37700072 -1.18738682]
[-2.30337426 -1.18738682 -0.46402358 -0.05702664  0.27592974  0.56682064
  1.37700072  1.49451522]


In [56]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [57]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## TODO Section

### Manipulação de Arrays

Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B

In [72]:
import numpy as np

A1 = [1,4,2,6,5,7,3,0]
B1 = [3,2,0,9,8,7]

C1 = np.setdiff1d(A1, B1)

print(C1)


A2 = np.array(A1)
B2 = np.array(B1)

C2 = np.setdiff1d(A2, B2)

print(C2)

# TODO: sua resposta aqui

[1 4 5 6]
[1 4 5 6]


### Manipulando arrays de acordo com valores escalares

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [ ]:


# TODO: sua resposta aqui

# Pandas

## Estrutura de Dados

In [73]:
from pandas import Series, DataFrame
import pandas as pd
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [74]:
print(obj.values)
print(obj.index) #obj.index.values

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [76]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [77]:
import numpy as np
print(obj2[(obj2 > 0) & (obj2 < 5)])
print(obj2 * 2)
print(np.exp(obj2))

d    4
c    3
dtype: int64
d     8
b    14
a   -10
c     6
dtype: int64
d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64


In [78]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [79]:
states = ['Oregon', 'Texas','California', 'Ohio']
obj4 = Series(sdata, index=states)
obj4

Oregon        16000.0
Texas         71000.0
California        NaN
Ohio          35000.0
dtype: float64

In [80]:
print(pd.isnull(obj4)) # == obj4.isnull()
print(pd.notnull(obj4))

Oregon        False
Texas         False
California     True
Ohio          False
dtype: bool
Oregon         True
Texas          True
California    False
Ohio           True
dtype: bool


In [81]:
print(obj3)
print(obj4)
obj3 + obj4

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
Oregon        16000.0
Texas         71000.0
California        NaN
Ohio          35000.0
dtype: float64


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [82]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
Oregon        16000.0
Texas         71000.0
California        NaN
Ohio          35000.0
Name: population, dtype: float64

In [83]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [84]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [86]:
df2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                index=['one', 'two', 'three', 'four', 'five'])
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [87]:
print(df['state'])
print(df.year)

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object
0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64


In [88]:
print(df2.loc['four']) #label
print(df.iloc[0]) #int

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object
state    Ohio
year     2000
pop       1.5
Name: 0, dtype: object


In [89]:
df2['debt'] = np.arange(5)

In [90]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
df2['debt'] = val
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [91]:
df2['eastern'] = df2.state == 'Ohio'
df2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [92]:
del df2['eastern']
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [93]:
df.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9]], dtype=object)

In [94]:
obj = Series(range(3), index=['a', 'b', 'c'])
obj.index.values

array(['a', 'b', 'c'], dtype=object)

In [95]:
print('state' in df2.columns)
print(0 in df.index)

True
True


## Aplicação de Função e Mapeamento

In [96]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [97]:
df = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
np.abs(df) #retorna valor absoluto

b         d         e
Utah    0.079393  0.107969  0.506951
Ohio    1.125589  1.008052  0.354829
Texas   0.702668  0.113451  1.041134
Oregon  0.686599  2.559448  0.946311

In [98]:
f = lambda x: x.max() - x.min()
print(df.apply(f))
print(df.apply(f, axis=1))

b    1.828258
d    2.672899
e    1.987444
dtype: float64
Utah      0.427558
Ohio      2.133642
Texas     1.154585
Oregon    3.505758
dtype: float64


In [99]:
def f2(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

df.apply(f2)

b         d         e
min -0.702668 -2.559448 -1.041134
max  1.125589  0.113451  0.946311

In [100]:
format2 = lambda x: '%.2f' % x
df.applymap(format2)

b      d      e
Utah     0.08   0.11   0.51
Ohio     1.13  -1.01   0.35
Texas   -0.70   0.11  -1.04
Oregon  -0.69  -2.56   0.95

## Ordenação e Ranking

In [101]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
df2 = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
print(obj)
print(df2)
print(obj.sort_index())
print(df2.sort_index())
print(df2.sort_index(axis=1))

d    0
a    1
b    2
c    3
dtype: int64
       d  a  b  c
three  0  1  2  3
one    4  5  6  7
a    1
b    2
c    3
d    0
dtype: int64
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
       a  b  c  d
three  1  2  3  0
one    5  6  7  4


In [102]:
obj = Series([4, 7, -3, 2])
obj.sort_values() #igual para pandas

2   -3
3    2
0    4
1    7
dtype: int64

In [103]:
df3 = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(df3)
print(df3.sort_index(by='b'))
print(df3.sort_index(by=['a','b']))

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1
   b  a
2 -3  0
3  2  1
0  4  0
1  7  1
   b  a
2 -3  0
0  4  0
3  2  1
1  7  1


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  after removing the cwd from sys.path.


In [108]:
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'nota': [8, 7.5, 7.5, 10, 5]}
df4 = DataFrame(data)
print(df4)
df4['rank'] = df4['nota'].rank(ascending=0)
df4.sort_values('rank')

    name  nota
0  Jason   8.0
1  Molly   7.5
2   Tina   7.5
3   Jake  10.0
4    Amy   5.0


name  nota  rank
3   Jake  10.0   1.0
0  Jason   8.0   2.0
1  Molly   7.5   3.5
2   Tina   7.5   3.5
4    Amy   5.0   5.0

## Sumarização e Estatística Descritiva

In [109]:
df5 = DataFrame([[1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
print(df5)
print(df5.sum())
print(df5.sum(axis=1))
print(df5.count())

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one    9.25
two   -5.80
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
one    3
two    2
dtype: int64


In [ ]:
df5.describe()

In [110]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [111]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

## Manipulação de Valores Faltantes 

In [112]:
string_data = Series(['laranja', 'uva', np.nan, 'abacate'])
print(string_data)
print(string_data.isnull())
string_data[0] = None
print(string_data.isnull())

0    laranja
1        uva
2        NaN
3    abacate
dtype: object
0    False
1    False
2     True
3    False
dtype: bool
0     True
1    False
2     True
3    False
dtype: bool


In [114]:
data = DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                  [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
print(data)
cleaned = data.dropna()
print('\n',cleaned)
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

      0    1    2
0  1.0  6.5  3.0


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [115]:
print(data.fillna(0))
print(data.fillna(data.mean()))

     0    1    2
0  1.0  6.5  3.0
1  1.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  6.5  3.0
     0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0


## TODO Section

### Manipulação de DataFrame

        > Crie, a partir do dicionário abaixo, um DataFrame cujo index seja os valores da variável labels
        > encontre a média dos valores da coluna age e preencha os valores faltantes dessa coluna com o valor da média
        > crie uma nova coluna chamada 'rank', que mostre os animais que receberam mais visitas
        > qual o animal que recebeu a maior quantidade de visitas?

In [133]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']



In [134]:
import pandas as pd
import numpy as np

data_aux = DataFrame(data, index = labels)

print("Resposta 1:")
print(data_aux)

data_aux2 = data_aux.fillna(data_aux['age'].mean())
print("Resposta 2:")
print(data_aux2)


data_aux2['rank'] = data_aux2['visits'].rank()
data_aux2.sort_values('rank', ascending=True)
print("Resposta 3:")
print(data_aux2)


Resposta 1:
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
Resposta 2:
  animal     age  visits priority
a    cat  2.5000       1      yes
b    cat  3.0000       3      yes
c  snake  0.5000       2       no
d    dog  3.4375       3      yes
e    dog  5.0000       2       no
f    cat  2.0000       3       no
g  snake  4.5000       1       no
h    cat  3.4375       1      yes
i    dog  7.0000       2       no
j    dog  3.0000       1       no
Resposta 3:
  animal     age  visits priority  rank
a    cat  2.5000       1      yes   2.5
b    cat  3.0000       3      yes   9.0
c  snake  0.5000       2       no   6.0
d    dog  3.4375       3      yes   9.0
e    dog  5.0000       2       no   6.0
f    cat 

In [ ]:
# TODO: sua resposta aqui