# Numpy

In [1]:
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [ ]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

## ndarray

In [ ]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

In [ ]:
print(arr1.shape)
print(arr1.dtype)

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print(arr2.size)

In [ ]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print(data4)
print(data5)

In [ ]:
data6 = np.arange(15)
print(data6)

In [ ]:
data7 = np.eye(5)
print(data7)

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2], dtype=np.int32)
print(arr2.dtype)

In [ ]:
arr1 + arr2

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

In [ ]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

## Operações entre arrays e escalares

In [ ]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

In [ ]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Escalar dividindo array: \n',1/arr3)
print('Array elevado ao quadrado: \n',arr3 ** 0.5)

## Indexação e Fatiamento

In [ ]:
arr = [2,14,3,6,8,3,10,222,4]
arr = np.array(arr)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

In [ ]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2]) #igual a print(arr2d[0, 2])

[7 8 9]
3


In [ ]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

## Transposição

In [ ]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

## Flattening

In [4]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
b2 = arr2d.ravel() 
b2[0] = 101
print(arr2d)

----- flatten() -----

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

----- ravel() -----

[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


In [5]:
arr2d[0]

array([101,   2,   3])

## Funções Universais

In [ ]:
arr = np.arange(10)
print(arr)
np.sqrt(arr) #raiz quadrada
np.exp(arr) #e^x

## Localização baseada em Condição e Métodos Estatísticos

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
print(arr)
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

In [6]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean()) #ou np.mean(arr)
print(arr.sum())
print(arr.mean(axis=1))
print(arr.sum(0))

[[ 0.57480532 -1.09279561  1.81457158 -0.51275426]
 [-1.45843057 -1.4349791  -0.49139296  1.40720842]
 [-0.39263311  0.92602305 -0.30267001 -1.01712897]
 [-1.62633392  0.00328054  0.72649851 -1.1376161 ]
 [-1.66054144 -1.69303861 -0.81765132  0.6448836 ]]
-0.3770347478746766
-7.540694957493533
[ 0.19595676 -0.49439855 -0.19660226 -0.50854274 -0.88158694]
[-4.56313372 -3.29150973  0.9293558  -0.6154073 ]


## Álgebra Linear

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

In [ ]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print(mat)
print(inv(mat)) #inversa

## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [ ]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

In [ ]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(42) # reset seed
print(np.random.random())

In [ ]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
np.random.shuffle(x)
x

## Vectorize

In [ ]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

In [ ]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

## Aplicar uma função – coluna ou linha

In [ ]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

In [ ]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

## Outros Métodos

In [ ]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

In [ ]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place
print(arr)

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

In [29]:
import numpy as np
import pandas as pd

## TODO Section

### Manipulação de Arrays

Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B

In [3]:
# TODO: sua resposta aqui
a = np.array([1,4,2,6,5,7,3,0])
b = np.array([3,2,0,9,8,7])

np.setdiff1d(a,b)

array([1, 4, 5, 6])

### Manipulando arrays de acordo com valores escalares

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [25]:
# TODO: sua resposta aqui
def interval(vetor,x = 6,y = 20):
    return np.sort(vetor[(vetor > x) & (vetor < y)])

In [26]:
vetor = np.array([10,3,7,5,8,23,15])
interval(vetor)

array([ 7,  8, 10, 15])

# Pandas

## Estrutura de Dados

In [ ]:
from pandas import Series, DataFrame
import pandas as pd
obj = Series([4, 7, -5, 3])
obj

In [ ]:
print(obj.values)
print(obj.index) #obj.index.values

In [ ]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

In [ ]:
import numpy as np
print(obj2[(obj2 > 0) & (obj2 < 5)])
print(obj2 * 2)
print(np.exp(obj2))

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

In [ ]:
states = ['Oregon', 'Texas','California', 'Ohio']
obj4 = Series(sdata, index=states)
obj4

In [ ]:
print(pd.isnull(obj4)) # == obj4.isnull()
print(pd.notnull(obj4))

In [ ]:
print(obj3)
print(obj4)
obj3 + obj4

In [ ]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = DataFrame(data)
df

In [ ]:
df2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                index=['one', 'two', 'three', 'four', 'five'])
df2

In [ ]:
print(df['state'])
print(df.year)

In [ ]:
print(df2.loc['four']) #label
print(df.iloc[0]) #int

In [ ]:
df2['debt'] = np.arange(5)

In [ ]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
df2['debt'] = val
df2

In [ ]:
df2['eastern'] = df2.state == 'Ohio'
df2

In [ ]:
del df2['eastern']
df2

In [ ]:
df.values

In [ ]:
obj = Series(range(3), index=['a', 'b', 'c'])
obj.index.values

In [ ]:
print('state' in df2.columns)
print(0 in df.index)

## Aplicação de Função e Mapeamento

In [ ]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [ ]:
df = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
np.abs(df) #retorna valor absoluto

In [ ]:
f = lambda x: x.max() - x.min()
print(df.apply(f))
print(df.apply(f, axis=1))

In [ ]:
def f2(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

df.apply(f2)

In [ ]:
format2 = lambda x: '%.2f' % x
df.applymap(format2)

## Ordenação e Ranking

In [ ]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
df2 = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
print(obj)
print(df2)
print(obj.sort_index())
print(df2.sort_index())
print(df2.sort_index(axis=1))

In [ ]:
obj = Series([4, 7, -3, 2])
obj.sort_values() #igual para pandas

In [ ]:
df3 = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(df3)
print(df3.sort_index(by='b'))
print(df3.sort_index(by=['a','b']))

In [ ]:
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'nota': [8, 7, 7.5, 10, 5]}
df4 = DataFrame(data)
print(df4)
df4['rank'] = df4['nota'].rank(ascending=0)
df4.sort_values('rank')

## Sumarização e Estatística Descritiva

In [ ]:
df5 = DataFrame([[1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
print(df5)
print(df5.sum())
print(df5.sum(axis=1))
print(df5.count())

In [ ]:
df5.describe()

In [ ]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

In [ ]:
mask = obj.isin(['b', 'c'])
mask

## Manipulação de Valores Faltantes 

In [ ]:
string_data = Series(['laranja', 'uva', np.nan, 'abacate'])
print(string_data)
print(string_data.isnull())
string_data[0] = None
print(string_data.isnull())

In [ ]:
data = DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                  [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
print(data)
cleaned = data.dropna()
print('\n',cleaned)
data.dropna(how='all')

In [ ]:
print(data.fillna(0))
print(data.fillna(data.mean()))

## TODO Section

### Manipulação de DataFrame

        > Crie, a partir do dicionário abaixo, um DataFrame cujo index seja os valores da variável labels
        > encontre a média dos valores da coluna age e preencha os valores faltantes dessa coluna com o valor da média
        > crie uma nova coluna chamada 'rank', que mostre os animais que receberam mais visitas
        > qual o animal que recebeu a maior quantidade de visitas?

In [9]:
import pandas as pd
import numpy as np

In [10]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [11]:
df = pd.DataFrame(data,index=labels)
print("--------------------- Média Coluna Age -------------",'\n')
df['age'] = df['age'].fillna(np.mean(df['age']))
print(df['age'])
print("--------------------- Rank dos animais -------------",'\n')
df['rank'] = df['visits'].rank()
df = df.sort_values(by = 'rank', ascending=False)
print(df.head())
print("--------------------- Quem recebeu mais visitas? --------------------",'\n')
df[df['visits']==(df['visits'].max())]

--------------------- Média Coluna Age ------------- 

a    2.5000
b    3.0000
c    0.5000
d    3.4375
e    5.0000
f    2.0000
g    4.5000
h    3.4375
i    7.0000
j    3.0000
Name: age, dtype: float64
--------------------- Rank dos animais ------------- 

  animal     age  visits priority  rank
b    cat  3.0000       3      yes   9.0
d    dog  3.4375       3      yes   9.0
f    cat  2.0000       3       no   9.0
c  snake  0.5000       2       no   6.0
e    dog  5.0000       2       no   6.0
--------------------- Quem recebeu mais visitas? -------------------- 



animal     age  visits priority  rank
b    cat  3.0000       3      yes   9.0
d    dog  3.4375       3      yes   9.0
f    cat  2.0000       3       no   9.0